#! /bin/sh

NAME=rtsp_multi_server_test
DAEMON=/usr/bin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    start-stop-daemon -S -q -x $DAEMON -- --video_type=H264 --width=1920 --heigh=1080 --audio_type=G711U --video1_path=/dev/video13 --video2_path=/dev/video14 
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
