#!/bin/sh

case "$1" in
  start)
    # if memory less than 256M, enable zram swap function
    total=`grep MemTotal /proc/meminfo | awk '{print $2}'`
    if [ $total -le 262144 ]; then
        face=10000
        echo 1 > /proc/sys/vm/overcommit_memory
        echo 2 > /sys/block/zram0/max_comp_streams
        echo lz4 > /sys/block/zram0/comp_algorithm
        echo 64M > /sys/block/zram0/disksize
        mkswap /dev/zram0
        swapon /dev/zram0
    else
        face=30000
    fi
    #export PATH=/usr/bin/:$PATH
    #256M DDR face number 10000, great than 256M DDR face number 30000
    export QT_QPA_FB_DRM=1
    export QT_QPA_PLATFORM=linuxfb:rotation=0
    QFacialGate -f $face &
    rtsp_multi_server_test --video_type=H264 --width=1920 --heigh=1080 --audio_type=G711U --video1_path=/dev/video13 --video2_path=/dev/video14 &

    #cd kvm

    ;;
  stop)
    killall QFacialGate 
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
